version: "3"
services:
  llava-cli:
    build: .
    container_name: "llava-cli"
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./llama.cpp:/projects"
    working_dir: /projects
